### ISSUE TITLE
Criar uma interface para a conexão com o backend

### ISSUE THREAD

**Issue by laisnuto** [Projeto-MAC-0350/projeto-mac350-front#4]
Como um desenvolvedor eu gostaria de ter um interface no front para fazer as requests no back.

Critério de aceitação:

- criar um objeto client que faça as request.
- incluir o get da distancia entre artistas
- configurar o API axios

**Comment by filipetressmann** [comment]
Resolvido [aqui](https://github.com/Projeto-MAC-0350/projeto-mac350-front/commit/d26b526481ecbe4d80b114e840f9dd9fea3c10fe)
